<a href="https://colab.research.google.com/github/vipinkumarcp/NLP_Practice/blob/main/FakenewsclassifierusingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

In [27]:
fake_news = pd.read_csv('/content/Fake.csv')

In [28]:
true_news = pd.read_csv('/content/True.csv')

In [29]:
fake_news.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [30]:
true_news.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [31]:
fake_news['label'] = 1

In [32]:
fake_news

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",1

In [33]:
true_news['label'] = 0

In [34]:
df = pd.concat([true_news,fake_news],ignore_index=True)

df = df.sample(frac=1).reset_index(drop=True)

In [35]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [36]:
X = df.drop('label',axis=1)

In [37]:
y = df['label']

In [38]:
X.shape

(44898, 4)

In [39]:
y.shape

(44898,)

In [40]:
import tensorflow as tf

In [41]:
tf.__version__

'2.19.0'

In [42]:
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [43]:
#vocabulary size
voc_size = 5000

In [44]:
#one hot respresentation
messages = X.copy()

In [45]:
messages['title'][1]

'Suspected U.S. drone strike targets militants in Pakistan, regional official says'

In [46]:
messages

,title,text,subject,date
0,TOMI LAHREN: “AFTER 8 YEARS…We were part of a ...,,politics,"Jan 26, 2017"
1,Suspected U.S. drone strike targets militants ...,"PARACHINAR/PESHAWAR, Pakistan (Reuters) - A su...",worldnews,"September 15, 2017"
2,U.S. ally seen clinching re-election in Hondur...,TEGUCIGALPA (Reuters) - Eight years after a co...,worldnews,"November 23, 2017"
3,"U.S. looks to Facebook, private groups to batt...","WASHINGTON (Reuters) - The U.S. government, ac...",politicsNews,"February 25, 2016"
4,Senate votes to confirm Gottlieb as head of FDA,(Reuters) - The U.S. Senate voted on Tuesday t...,politicsNews,"May 9, 2017"
...,...,...,...,...
44893,Iraq steps up retaliation against Kurdish inde...,BAGHDAD (Reuters) - Iraq stopped selling dolla...,worldnews,"October 3, 2017"
44894,Investors buoyed by Trump's readiness to move ...,(Reuters) - Wall Street’s predilection for a g...,politicsNews,"March 24, 2017"
44895,Nine killed as burqa-clad Taliban attack Pakis...,"PESHAWAR, Pakistan (Reuters) - Pakistani Talib...",worldnews,"December 1, 2017"
44896,Canada's Trudeau warns against 'tempting short...,"PROVIDENCE, R.I. (Reuters) - Canadian Prime Mi...",politicsNews,"July 14, 2017"
44897,U.S. appeals injunction of Trump revised trave...,SAN FRANCISCO (Reuters) - The U.S. Justice Dep...,politicsNews,"March 30, 2017"

In [47]:
#messages.reset_index(inplace=True)

In [48]:
messages

,title,text,subject,date
0,TOMI LAHREN: “AFTER 8 YEARS…We were part of a ...,,politics,"Jan 26, 2017"
1,Suspected U.S. drone strike targets militants ...,"PARACHINAR/PESHAWAR, Pakistan (Reuters) - A su...",worldnews,"September 15, 2017"
2,U.S. ally seen clinching re-election in Hondur...,TEGUCIGALPA (Reuters) - Eight years after a co...,worldnews,"November 23, 2017"
3,"U.S. looks to Facebook, private groups to batt...","WASHINGTON (Reuters) - The U.S. government, ac...",politicsNews,"February 25, 2016"
4,Senate votes to confirm Gottlieb as head of FDA,(Reuters) - The U.S. Senate voted on Tuesday t...,politicsNews,"May 9, 2017"
...,...,...,...,...
44893,Iraq steps up retaliation against Kurdish inde...,BAGHDAD (Reuters) - Iraq stopped selling dolla...,worldnews,"October 3, 2017"
44894,Investors buoyed by Trump's readiness to move ...,(Reuters) - Wall Street’s predilection for a g...,politicsNews,"March 24, 2017"
44895,Nine killed as burqa-clad Taliban attack Pakis...,"PESHAWAR, Pakistan (Reuters) - Pakistani Talib...",worldnews,"December 1, 2017"
44896,Canada's Trudeau warns against 'tempting short...,"PROVIDENCE, R.I. (Reuters) - Canadian Prime Mi...",politicsNews,"July 14, 2017"
44897,U.S. appeals injunction of Trump revised trave...,SAN FRANCISCO (Reuters) - The U.S. Justice Dep...,politicsNews,"March 30, 2017"

In [49]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [50]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [51]:
corpus

['tomi lahren year part differ march march vote booth vote trump video',
 'suspect u drone strike target milit pakistan region offici say',
 'u alli seen clinch elect hondura vote eight year coup',
 'u look facebook privat group battl onlin extrem',
 'senat vote confirm gottlieb head fda',
 'boom sarah huckabe sander set media straight differ trump volunt meet clinton dnc pay million fake russian dossier',
 'u n mediat de mistura attend syria talk friday report',
 'jill stein demand recount hillari camp use desper effort stop trump hillari clinton will risk civil war america video',
 'drain obama radic swamp rep chaffetz call obama appoint fed gov ethic director uneth public critic trump',
 'wow confirm ice time deport illeg alien protect sanctuari counti suspect arsonist behind worst fire ca histori',
 'republican disarray deepen trump attack rebel conserv',
 'woman want elect bulli whose campaign work shadi oper incit violenc women children senior citizen video',
 'canada g presid focu women gender equal trudeau',
 'white back democrat prove obsess race one ridicul photo',
 'merkel tri build coalit vote put far right parliament',
 'spain give catalan leader day drop independ',
 'canada propos helicopt u n mali mission sourc',
 'kind woman bring beer report hurrican report galveston beer video',
 'jim beam fan call boycott spokesperson liber actress brag taunt vp mike penc defend life',
 'u tillerson concern saudi purg monitor hariri situat',
 'u rule possibl oil embargo venezuela haley',
 'madrid repres catalonia apolog polic violenc independ vote',
 'u back syrian fighter say let govern forc cross euphrat',
 'video dinesh souza warn us world would look like gave obama anoth term obama america correct',
 'wow wikileak email show hillari bankrupt gun manufactur execut order video',
 'saudi air strike yemen intensifi resid capit stay indoor',
 'colombia halt cano limon pipelin rebel attack sourc',
 'zimbabw war vet leader say mugab impeach',
 'senior intellig offici slam trump ground intellig brief',
 'divid iraq test u influenc fight islam state wane',
 'pb host ask hillari believ presid racist answer prove real racist video',
 'hilari cnn presid jeff zucker hitler video',
 'berni sander destroy trump coron comfort armchair',
 'matt lauer ask obama former cia director trump inner circl prepar tackl lock room keep trump use nuclear weapon video',
 'u withhold clinton email top secret inform',
 'pope candidli admit church arriv late confront abus',
 'uk mr brexit say vacanc ambassador unit state',
 'grab popcorn queen corrupt deni special treatment first debat',
 'divid syria u strike welcom condemn',
 'trump blame media conspiraci low number latest unhing twitter rant tweet',
 'libyan forc hit islam state camp air strike command',
 'czech elect websit hack vote unaffect statist offic',
 'head homeland secur destroy ted cruz ask extrem dumb question hear video',
 'break trump announc nomine secretari state liber head explod',
 'trump tariff plan could boomerang spark trade war china mexico',
 'watch rabid trump support call liber genocid frighten arizona ralli',
 'video chicago thug presid goe trump outrag attack',
 'democrat rep sexual assault woman fault appear invit video',
 'comoro lawmak lead citizenship inquiri attack',
 'us admit target al nusra blame moscow separ moder terrorist',
 'realli mean hillari support video',
 'kushner look buyer new york observ report',
 'jay dyer tragedi hope part rothschild central bank fdr us imperium',
 'saudi led coalit reopen yemeni al wadea border cross sourc',
 'guess suprem court justic got caught sleep case imag',
 'republican go back basic stop ask russia investig hillari',
 'maxin water torch trump lie lack transpar gloriou tweet storm',
 'forget russia realli affect elect pro hillari detroit citi clerk hire illiter poll worker',
 'break hous intel launch investig leak fbi better good answer',
 'trump get hilari mock look wife shoulder vote',
 'trump name cruz alli mike lee possibl suprem court justic',
 'santilli freed plea pact vega shoot cast shadow bundi trial',
 'trump say presid activ sue media outlet neg report video',
 'video cnn co anchor chri cuomo obviou obsess discredit black gop candid ben carson would consid racist carson democrat',
 'trump nomin elain chao transport post sourc',
 'philippin lawmak approv one yr extens martial law south',
 'north korea threat agenda south korean foreign minist visit japan',
 'big question whether rohingya go home u n refuge chief',
 'kim jong un north korean media enthusiast want trump becom presid',
 'debbi wasserman schultz plan continu pay muslim aid charg multipl count bank fraud live pakistan tell author muslim wife left countri crimin investig',
 'wow huckabe ask nanci pelosi racist dumb dr ben carson comment',
 'embarrass nyc mayor de blasio tell differ trump obama immigr polici video',
 'spain suspend catalonia autonomi respons independ threat',
 'trump son law met execut sanction russian bank testifi',
 'netanyahu meet clinton trump u visit sourc',
 'full interview judg jeanin pirro depth interview presid trump video',
 'wow one courag man stand rioter hold best sign ever',
 'watch stephen king tell absolut truth mass shoot continu america',
 'republican hous speaker ryan told trump retir report rumor true white hous',
 'hillari confidant ask run give stun answer confirm think video',
 'let hillari hijack flint water crisi audit find state regul fault',
 'wow pope franc tell journalist peopl believ man made climat chang stupid stubborn',
 'ex fbi agent navi seal russian interfer lie spread intellig commun like hitler mein kampf video',
 'trump support terror american woman subway wear hijab',
 'minnesota mayor classic liber meltdown white privileg denier video',
 'ben cohen respons fox news berni sander conspiraci theori perfect video',
 'math behind trump never presid',
 'republican brag trump inaugur broke record record',
 'bill clinton lost watch yank balloon littl girl dnc celebr super senior moment video',
 'south korea warn north repeat armistic violat',
 'comedi gold detroit news willi dump tire wrong spot video',
 'video prove ted cruz even creepier thought video',
 'oop media think voter would forget hillari friend mentor late kkk leader robert byrd video',
 'john oliv mercilessli take apart gop make bullshit rule video',
 'china hand harshest sentenc yet crackdown activist',
 'wow hillari support caught undercov camera say okay rip republican voter registr video',
 'u charg former turkish minist iran sanction evas',
 'break obama break democrat rank throw hillari bu fbi investig',
 'watch trump campaign spokeswoman say presid obama start war afghanistan',
 'trump push drugmak lower price u product',
 'french foreign minist travel libya push peac deal',
 'watch hilari video show reddit user apolog terror organ cnn threaten public',
 'donna brazil destroy palin blame woman beat son arrest obama video',
 'saudi led coalit allow crane yemen hodeidah port',
 'trump immigr pitch fall flat republican near border',
 'white hous say execut order appli independ regul',
 'senat mccaskil absent three week cancer treatment',
 'london angel station reopen suspect packag scare',
 'democrat senat murray think bipartisan obamacar deal still possibl',
 'justic depart civil right probe arizona elect',
 'nbc manag protect sh detail marri matt lauer disgust act sexual harass reveal democrat fan boy fire',
 'break obama holder fast n furiou rifl found el chapo hideout capabl down helicopt',
 'classless kennedi famili histori philand drunk murder rapist celebr independ day mock trump',
 'transpar trade bill transpar administr histori',
 'iran guard flex muscl middl east despit trump warn',
 'video joe biden think china north america',
 'factbox trump twitter nov nfl first ladi',
 'syrian armi cut islam state main deir al zor suppli line ria',
 'defens secretari matti speak incompet trump threat north korea video',
 'kid serial liar brian william blame fake news hillari loss msnbc last night video',
 'three kurdish fighter kill five wound blast south oil citi kirkuk',
 'republican tri pick piec healthcar defeat',
 'brazil temer sent test treatment urinari obstruct',
 'interact trump hate map prove danger america',
 'new book reveal hillari anti semit side blame bill campaign manag lose congression race call f cking jew b stard',
 'world largest amphibi aircraft make maiden flight china',
 'obama threaten surfac leftist bunker speak trump plan end daca',
 'second woman enter russian presidenti race campaign singl mother',
 'eu call legal commiss vet new polish judici reform law',
 'russia accus u deni entri senior militari offici',
 'christian group fear target fake hate group list releas cnn',
 'obama sign star war ii defens bill hypocrisi blame trump arm race',
 'barca valverd skirt independ debat iniesta rule bilbao',
 'wow russian lawyer met donald trump jr seen photo person tie obama day meet',
 'obama launch mission cure cancer',
 'boiler room presid trump great neo liber freakout',
 'hilari liber stun republican guest play race bait game msnbc host cut interview video',
 'kuwait say gcc keep oper despit qatar crisi',
 'awesom pro trump latino tell horror social trump candid video',
 'tucker carlson unload dem strategist post huntrepublicancongressmen day republican shot berni sander support unbalanc person video',
 'embarrass obama explain rebuk isi attend climat chang summit video',
 'boiler room behold new ministri truth',
 'twitter lay gop leader amazingli wishi washi statement trump anti muslim hate',
 'white vote save trump republican screw',
 'billionair liber governor boost state economi tax rich',
 'happi th juli american incom inequ hit histor high',
 'u republican congressman labrador run idaho governor idaho tv station',
 'nation affect u immigr order may stay list',
 'trump consid lawyer white hous russia role sourc',
 'new blow campaign trump foundat order halt fundrais',
 'around peopl injur swiss train collis polic',
 'must see result new poll ask american one word associ hillari',
 'video un climat chang freak make everi effort decreas world popul',
 'chill fox report jame rosen recount spi obama mafia video',
 'analyst visit moscow find russian laugh us putin manipul fool trump video',
 'justic depart seek time trump wiretap evid',
 'aid group seek million help million rohingya muslim flee myanmar',
 'two week elect poll show carter vs reagan reagan landslid trump like',
 'kurdish leader barzani condemn iraqi parliament vote remov kirkuk governor kurdish media',
 'cliven bundi son occupi oregon wildlif reserv arm militia u patriot video',
 'famili san bernardino shoot sue facebook googl twitter',
 'senat warren seek investig insur retir rule',
 'senat republican leader say daca part border secur discuss',
 'london angel underground station close due secur alert',
 'repeat deceit us tri link iran al qaeda',
 'buy american even trump maga gear sold via canada america',
 'philippin set keep open pit mine ban dutert reject call lift',
 'watch epic video truth teller colonel ralph peter suspend fox news use tough languag describ obama',
 'democrat introduc new bill russia iran sanction',
 'donald trump accus sexual assault mexico',
 'germani displac resid make way syrian refuge nurs shock kick flat year',
 'bird feather harvey weinstein help bill clinton defend monica lewinski scandal',
 'hospit stock fall republican health bill seen leav million uninsur',
 'watch sarah palin dehuman black peopl thug peopl',
 'loudmouth rosi donnel bulli wrong trump outrag melania threaten lawsuit rosi push fals video twitter yr old barron',
 'white hous support renew spi law without reform offici',
 'retir gener ex cia chief david petraeu receiv punish',
 'russia saudi arabia cement new friendship king visit',
 'kenya polic dispers protest odinga temper vote protest call',
 'senat mccain say offer afghanistan strategi septemb',
 'senil truth bomb bill clinton crowd sometim wish marri video',
 'hedg fund founder scaramucci join trump white hous liaison',
 'session panic cancel public testimoni want answer question russia',
 'everyon freak visitor berni sander ralli video tweet',
 'judg hand illeg alien tri kill trump shock plea deal',
 'lol fakenew cnn april ryan embarrass thanksgiv day obsess legitimaci sarah sander pecan pie',
 'gop senat enough fire mueller could end trump presid video',
 'euro zone germani schaeubl face new challeng far right',
 'top democrat activist launch onlin campaign threaten bulli yr old conserv face charg video',
 'vice presid biden chide turkey freedom express',
 'senat mccain suggest subpoena make white hous cyber aid testifi',
 'video dalla shoot agenda',
 'oop attorney gener lynch slip sign technic interfer russian',
 'exclus iraq hold foreign wive children suspect islam state fighter',
 'year old man reportedli cabin fever one month new job',
 'exclus trump target illeg immigr given repriev deport obama',
 'texa four state sue u transgend health polici',
 'lip teeth china tie north korea fray',
 'watch cop caught video say black violent tendenc',
 'real time panelist discuss dem sit thing get problemat real fast video',
 'portland antifa throw firework polic patriot prayer ralli video',
 'syrian armi alli reach airbas besieg islam state eastern syria command',
 'clinton slip step behind biden awkward linger hug uncl joe earlier day video',
 'rebuk clinton email use creat open trump',
 'lead u senat urg chang foreign invest rule',
 'yahoo share fall latest secur breach',
 'time stop excus trump support start shame aw peopl',
 'wow liber fox news host geraldo rivera slam hypocrisi left ignor sexual assault alleg bill clinton',
 'cop put trump back breitbart shame fake muslim mob attack stori',
 'myanmar suu kyi work get aid rohingya mcconnel',
 'suprem court breath new life trump travel ban',
 'fantast trump point plan reform healthcar begin bombshel',
 'russian bomber strike islam state target syria ria',
 'mike ditka slam nfl player oppress last year respect countri countri play footbal',
 'thailand plan joint arm factori china',
 'australian pm say first refuge resettl u swap deal',
 'u extend iran sanction relief nuclear deal',
 'senat intellig chairman plan public hear russia',
 'break devic bust hillari clinton discov ten thousand email',
 'googl ceo shred trump immigr ban bad busi famili',
 'reuter say reason confid republican win white hous',
 'black lawyer editor legal websit write black juror automat vote free black person accus murder commit crime white person regardless evid',
 'itali pm plan shift militari forc iraq niger',
 'trump support caught racist meltdown wait coffe video',
 'high school teacher ask student pretend muslim',
 'hous speaker ryan option open zika fund',
 'hous speaker ryan say trump comment hispan judg racist',
 'obama parti blacklivesmatt organ white hous eve fbi terror attack confirm video',
 'death toll egypt mosqu attack climb state televis',
 'hard bitten rural south carolina mani mind made clinton',
 'break massachusett offici wait long releas video show thug shoot polic offic face video',
 'american tourist attack acid french train station',
 'north korea kim jong un consid use year old biplan go undetect modern radar',
 'boom truth fake news websit butt hurt rig media desper salvag scrap credibl video',
 'obama big billion dollar bailout puerto rico horizon becom st state video',
 'guess baltimor school system rank among nation largest school district',
 'histori channel classif elect make trump support lose sh',
 'texa lt governor use fake statist defend new open carri law video',
 'friend barack son beau got sick bring joe biden brink tear video',
 'zimbabwean south africa hope chang home armi seiz power',
 'trump thank putin slash us embassi staff cut payrol',
 'first ladi make surpris visit hospit visit children dr seuss day video',
 'presid obama arriv cuba',
 'trump new travel ban rais bar legal challeng',
 'watch megyn kelli own transphob texa lt governor bathroom law',
 'clinton win big new york democrat primari imag video',
 'eric boll accus serial sexual harass accus p ssi hat wear trump hate left wing activist professor',
 'keith olbermann buri trump whine recount effort',
 'obama argentina macri discuss brazil polit crisi',
 'border patrol agent rat dh govern secretli put illeg alien buss dump unsuspect commun across america',
 'obama new improv fbi offer huge reward anyon help frame white cop black thug shoot',
 'trump close name congressman price health secretari atlanta journal constitut',
 'japan dentsu get small fine overtim breach despit outcri',
 'unaccept high number afghan flee militari train u report',
 'shell air strike philippin troop hunt milit marshland',
 'hous dem erupt hous floor publicli shame speaker ryan gun law',
 'compet effort end south sudan war prolong conflict u n panel',
 'boiler room ep never end chao',
 'bust one nation biggest polit donor caught funnel money hillari crook democrat video',
 'campaign urg u public pension fund divest owner trump hotel',
 'hillari plan destroy trump upcom speech tie disturb alt right',
 'democrat congresswoman obama work hand hand islam extremist send troop harm way video',
 'dan rather mueller russia investig trump seiz fear',
 'conserv messag dreamer scream presid hilari',
 'venezuela opposit coalit split ahead new vote',
 'embroil controversi trump seek boost foreign trip',
 'mom columbin shooter shame nra gun crazi republican',
 'charlottesvil violenc test trump presidenti mettl',
 'actor blew million fortun worri play ronald reagan posit light upcom movi could ruin career',
 'stephen colbert gave us futurist view trump presid far video',
 'white cathol schoolkid threaten lynch black classmat video',
 'german offici warn civil war muslim non muslim somewher edg anarchi slide toward civil war',
 'lebanon armi chief warn israel threat amid polit crisi',
 'stockholm studi us europ top arm trade global saudi arabia weapon import skyrocket percent',
 'donald trump jr wreck fake indian elizabeth warren twitter conserv cheer',
 'unreal demot deputi ag bail interview senat intellig committe today',
 'big financi woe linger illinoi new budget',
 'ouch new email show hillari want fli plane michel obama',
 'predict white hous lie forc deputi attorney gener rosenstein quit',
 'turkey erdogan say discuss syrian dialogu congress russia putin',
 'republican plan strangl suprem court death retali hillari victori',
 'face time may uk listen banker brexit worri',
 'hous vote kill consum lawsuit rule',
 'republican senat mccain return tuesday healthcar vote',
 'anti govern terrorist forgot snack want send via u mail',
 'exclus america hilari poem describ america look like year presid trump',
 'vote plu marathon spell super busi sunday berlin polic',
 'least civilian kill coalit strike iraq syria report',
 'hard core ten gitmo detaine releas oman',
 'unhing trump support visit dc inaugur celebr spit migrant kid tweet',
 'venic commiss polish judiciari reform pose seriou risk',
 'fbi creat domest terror unit state',
 'trump say iran violat spirit iran nuclear deal',
 'watch trump deplor fan attack mom disabl daughter leav ralli',
 'ex trump advis bannon polici win loss',
 'venezuela arrest ex oil boss graft widen purg',
 'japan pm say forex polici discuss leader',
 'chuck todd grill trump attack clinton first divorc ugli video',
 'trump resign trump organ white hous',
 'respect forens pathologist suggest trump putin might actual poison hillari tweet',
 'challeng trump immigr order spread u state',
 'insid look obama star summer vacat retreat meanwhil american take vacat summer',
 'break turn bow b someth els common video',
 'wapo trump plan go around senat replac session loyal stoog',
 'nyt bombshel trump mcconnel speak mcconnel question trump gop futur',
 'episod network sunday wire hesher funk oul patrick henningsen live iraq',
 'greek pension protest govern took everyth',

In [52]:
corpus[1]

'suspect u drone strike target milit pakistan region offici say'

In [53]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[4338, 1809, 1189, 251, 3132, 2831, 2831, 4784, 16, 4784, 1612, 847],
 [3048, 4692, 1740, 1690, 4290, 1662, 535, 1194, 1674, 165],
 [4692, 2863, 3732, 2943, 3976, 2906, 4784, 2867, 1189, 3922],
 [4692, 2420, 85, 1432, 4370, 4260, 3582, 1595],
 [116, 4784, 785, 1294, 76, 4447],
 [1254,
  4266,
  1960,
  3510,
  1239,
  900,
  1089,
  3132,
  1612,
  2599,
  4794,
  2823,
  1889,
  3255,
  208,
  4614,
  156,
  1449],
 [4692, 1059, 3142, 3398, 4495, 474, 1496, 1914, 446, 4825],
 [2297,
  4837,
  1232,
  1451,
  4435,
  2091,
  1692,
  3657,
  1385,
  3207,
  1612,
  4435,
  2823,
  2848,
  3304,
  2405,
  3193,
  1132,
  847],
 [346,
  2727,
  547,
  3637,
  4250,
  1001,
  3311,
  2727,
  4441,
  1560,
  2383,
  3685,
  957,
  991,
  2938,
  2649,
  1612],
 [3239,
  785,
  323,
  1202,
  4027,
  3824,
  2913,
  3016,
  4323,
  2148,
  3048,
  3397,
  813,
  989,
  3067,
  1561,
  4963],
 [1236, 336, 635, 1612, 1190, 2701, 313],
 [2603,
  767,
  3976,
  417,
  4811,
  3195,
  1414,
  2992,
  250,
  2802,
  2689,
  4745,
  1287,
  1388,
  382,
  847],
 [1847, 1735, 990, 4585, 4745, 3704, 3679, 4466],
 [328, 4524, 499, 4001, 1887, 353, 4979, 3533, 686],
 [1048, 4245, 2217, 1849, 4784, 3574, 1984, 1859, 3385],
 [4994, 2295, 4931, 3096, 2537, 333, 546],
 [1847, 1825, 1901, 4692, 1059, 3198, 3508, 930],
 [3123, 2603, 3143, 1137, 4825, 984, 4825, 1783, 1137, 847],
 [2794,
  3855,
  2456,
  3311,
  3086,
  2512,
  3824,
  2505,
  2492,
  4663,
  1441,
  174,
  2957,
  3785,
  4185],
 [4692, 4118, 1799, 2302, 2536, 757, 4066, 794],
 [4692, 1460, 2622, 344, 915, 1774, 3031],
 [3461, 2740, 4762, 4891, 4455, 2689, 546, 4784],
 [4692, 4524, 2870, 3977, 165, 958, 3583, 4232, 3407, 2535],
 [847,
  554,
  397,
  1948,
  3393,
  2741,
  3275,
  2420,
  2324,
  88,
  2727,
  3264,
  4664,
  2727,
  1132,
  1803],
 [3239, 3437, 1981, 4004, 4435, 3383, 2754, 4212, 134, 4341, 847],
 [2302, 3138, 1690, 4582, 1683, 2198, 4587, 98, 985],
 [1349, 3426, 3620, 4917, 4002, 2701, 1190, 930],
 [3911, 3193, 478, 3096, 165, 2566, 2187],
 [1388, 3221, 1674, 3285, 1612, 2662, 3221, 4454],
 [4858, 3949, 1901, 4692, 2176, 2518, 530, 1280, 2927],
 [4963, 2570, 1123, 4435, 2618, 990, 137, 1253, 4001, 1022, 137, 847],
 [1658, 1479, 990, 2850, 848, 1218, 847],
 [3627, 3510, 3374, 1612, 605, 1179, 2040],
 [4561,
  3410,
  1123,
  2727,
  2259,
  163,
  957,
  1612,
  1020,
  4901,
  1878,
  1002,
  4636,
  2603,
  1191,
  1612,
  1692,
  3461,
  594,
  847],
 [4692, 3364, 2823, 1981, 3668, 1671, 406],
 [2823, 767, 4196, 1108, 4547, 2988, 847, 589],
 [4184, 2885, 1624, 165, 2206, 4215, 4106, 1280],
 [3470, 3690, 1181, 3156, 3447, 4358, 2361, 642, 2012],
 [4858, 1496, 4692, 1690, 4444, 4179],
 [1612, 3581, 900, 1733, 457, 404, 2269, 494, 3473, 3401, 2921],
 [1741, 4232, 4878, 530, 1280, 2091, 3138, 1690, 515],
 [1392, 3976, 2683, 940, 4784, 932, 2706, 1474],
 [76, 414, 2088, 3374, 2393, 1185, 1123, 1595, 4239, 4869, 2976, 847],
 [3733, 1612, 3637, 4511, 3851, 1280, 3824, 76, 3269],
 [1612, 4105, 1057, 1988, 1070, 3113, 3994, 3193, 2166, 1990],
 [118, 1197, 1612, 214, 3311, 3824, 524, 1512, 4059, 2631],
 [847, 4638, 3150, 990, 128, 1612, 2181, 1190],
 [499, 4250, 1937, 4117, 2603, 2789, 3211, 403, 847],
 [291, 2283, 2881, 282, 435, 1190],
 [3393, 4196, 4290, 244, 2229, 3581, 2769, 3498, 3711, 1628],
 [3611, 1623, 4435, 214, 847],
 [805, 2420, 226, 4830, 3133, 3163, 4825],
 [3589, 4456, 1281, 4649, 251, 1877, 837, 2433, 3824, 3393, 9],
 [2302, 4258, 1849, 2139, 3223, 244, 4505, 1539, 3407, 930],
 [1283, 4426, 842, 4695, 4238, 539, 4877, 1166, 2633],
 [1236, 2452, 4524, 4967, 3207, 1123, 3380, 1334, 4435],
 [3767, 4230, 4034, 1612, 1109, 1103, 4975, 1295, 2921, 4431],
 [2365,
  3380,
  3611,
  307,
  3976,
  3970,
  4435,
  1707,
  2018,
  2146,
  531,
  4499,
  1465,
  3245],
 [3733, 3104, 4914, 709, 1334, 386, 4149, 3302, 1373, 1253],
 [1612, 4029, 1658, 2628, 2420, 2246, 3625, 4784],
 [1612, 4291, 1185, 2863, 174, 4996, 2622, 4426, 842, 4695],
 [2083, 161, 1869, 2301, 2405, 890, 2842, 17, 4508, 304],
 [1612, 165, 990, 4798, 4627, 900, 1997, 2230, 4825, 847],
 [847,
  1479,
  794,
  1053,
  4076,
  977,
  1661,
  1887,
  3535,
  431,
  1189,
  3007,
  277,
  3756,
  3275,
  3969,
  137,
  3756,
  499],
 [1612, 4110, 1630, 344, 3938, 4378, 930],
 [4845, 2283, 1557, 4979, 2008, 2451, 3279, 928, 2995],
 [4281, 2227, 2526, 3064, 2995, 4292, 1349, 760, 4876, 1018],
 [2555, 4869, 4324, 2772, 2452, 473, 4692, 1059, 3684, 2808],
 [3037, 949, 3304, 4281, 4292, 900, 2915, 767, 1612, 4471, 990],
 [1454,
  3696,
  3500,
  1057,
  2843,
  3255,
  4268,
  3130,
  3834,
  3630,
  1581,
  2433,
  3839,
  1355,
  535,
  4105,
  2382,
  4268,
  2246,
  4605,
  3783,
  994,
  1334],
 [3239, 1960, 1123, 4908, 3048, 137, 4239, 849, 277, 3756, 3783],
 [4809, 1576, 4558, 3398, 382, 4105, 3132, 1612, 2727, 4482, 661, 847],
 [4994, 4284, 4762, 4107, 1149, 546, 2526],
 [1612, 890, 928, 497, 134, 3583, 156, 2433, 933],
 [131, 4794, 2823, 1612, 4692, 4876, 930],
 [4661, 2079, 2033, 3086, 2854, 4971, 2079, 990, 1612, 847],
 [3239, 4979, 2163, 1420, 2968, 2587, 4777, 2680, 495, 2159],
 [118, 2486, 2894, 4105, 4251, 4495, 4357, 890, 2843, 1132],
 [1236, 3104, 1493, 2506, 1365, 1612, 3033, 4825, 4711, 2051, 328, 3104],
 [4435, 3063, 1123, 2252, 2295, 878, 1253, 785, 515, 847],
 [958, 4435, 3214, 1924, 4230, 2895, 3496, 685, 1280, 4221, 2789],
 [3239,
  2823,
  1517,
  4105,
  1356,
  1433,
  2618,
  1420,
  3148,
  2658,
  3174,
  3636,
  3804],
 [49,
  4149,
  3727,
  647,
  3179,
  156,
  1789,
  1109,
  2823,
  3221,
  2253,
  2324,
  1218,
  1796,
  2234,
  847],
 [1612, 214, 3859, 1796, 2603, 4699, 1843, 701],
 [1730, 4558, 2878, 3824, 1198, 328, 2404, 4461, 847],
 [277, 1952, 1149, 1862, 3330, 3627, 3510, 1733, 3277, 2303, 847],
 [4305, 813, 1612, 3433, 990],
 [1236, 2492, 1612, 4210, 4055, 1496, 1496],
 [2578,
  2823,
  2889,
  118,
  3512,
  4676,
  3942,
  4199,
  1889,
  1546,
  4240,
  1388,
  1600,
  847],
 [2995, 2227, 1948, 4281, 2057, 3679, 4144],
 [3148, 2753, 1707, 3330, 3862, 1305, 4265, 2766, 2257, 847],
 [847, 4001, 2393, 1185, 3958, 3167, 4909, 847],
 [3955,
  900,
  515,
  3002,
  3275,
  2365,
  4435,
  1567,
  3992,
  2988,
  1572,
  3096,
  3261,
  397,
  847],
 [4384, 2328, 4513, 410, 406, 1189, 1850, 3785, 1460, 847],
 [2166, 2095, 3986, 4025, 385, 1116, 1015],
 [3239, 4435, 214, 539, 2154, 2276, 165, 2956, 2089, 1236, 3002, 1743, 847],
 [4692, 3834, 2259, 4317, 760, 2503, 3583, 4606],
 [3733, 2727, 3733, 499, 91, 3693, 4435, 4585, 4149, 1334],
 [118, 1612, 3195, 3030, 165, 990, 2727, 4207, 3193, 4449],
 [1612, 1146, 4167, 2521, 3060, 4692, 276],
 [3054, 1349, 760, 4101, 611, 1146, 2063, 1325],
 [118, 1658, 847, 4004, 4207, 2625, 4891, 3859, 3953, 1479, 4843, 2938],
 [3689, 1415, 3374, 146, 3581, 2603, 2783, 890, 4230, 2727, 847],
 [2302, 4258, 1849, 4549, 427, 4582, 1539, 4199],
 [1612, 4482, 3200, 92, 2204, 1236, 1585, 1539],
 [328, 3104, 165, 134, 4341, 1244, 546, 4221],
 [116, 2032, 409, 4840, 1151, 2477, 2361],
 [4832, 3245, 48, 2139, 3048, 3580, 329],
 [499, 116, 245, 515, 4911, 2033, 1325, 3750, 2622],
 [4695, 4949, 2405, 1859, 4670, 4059, 3976],
 [2449,
  2866,
  3016,
  1577,
  1881,
  333,
  4561,
  3410,
  3512,
  323,
  1937,
  1947,
  836,
  499,
  2456,
  4240,
  3067],
 [3733,
  2727,
  1130,
  402,
  1059,
  3659,
  1861,
  2265,
  3486,
  2630,
  1044,
  1061,
  2271,
  1901],
 [4111, 2945, 3873, 4963, 1223, 601, 4584, 2171, 1546, 546, 2537, 2628, 1612],
 [4975, 3994, 2578, 4975, 373, 4963],
 [2503, 2741, 659, 1519, 4608, 1087, 3078, 1612, 1948],
 [847, 3488, 3555, 515, 2166, 4281, 1132],
 [3493, 1612, 3473, 1489, 2543, 642, 820],
 [2870, 3716, 1227, 530, 1280, 4517, 2736, 244, 1017, 3892, 882, 1619],
 [1820, 3851, 441, 30, 3858, 1612, 2526, 4281, 2227, 847],
 [1456,
  1871,
  4071,
  760,
  79,
  3581,
  4614,
  3330,
  4435,
  4346,
  2127,
  4293,
  2872,
  847],
 [4840, 3834, 3977, 118, 187, 1059, 2604, 2995, 344, 2018, 912],
 [1236, 4245, 2141, 3987, 3633, 3346],
 [1415, 3762, 1744, 1901, 2361, 4413, 1849],
 [2495, 1612, 2902, 4071, 4001, 4544, 1132],
 [4830,
  78,
  836,
  4435,
  4370,
  538,
  1792,
  3581,
  2578,
  3195,
  2866,
  4008,
  4905,
  353,
  3311,
  4306,
  4771,
  4053,
  1563,
  4003],
 [2741, 1767, 4055, 4417, 1850, 4428, 3625, 2166],
 [2727, 4843, 1205, 4298, 4618, 30, 1612, 1057, 4971, 910],
 [472, 2603, 4291, 156, 3855, 353, 3195, 287, 234],
 [573, 3311, 3290, 3450, 478, 4830, 2365, 2749, 1874, 928],
 [3380, 3733, 4692, 3447, 2250, 1388, 1511, 1674],
 [1853, 4370, 874, 4290, 4614, 2902, 4370, 4906, 2688, 1479],
 [2727, 495, 3909, 3193, 3114, 1820, 2578, 1133, 3581, 1612, 2855, 353],
 [3246, 4087, 2946, 546, 2012, 2953, 1460, 3702],
 [3239,
  156,
  4246,
  497,
  1287,
  1612,
  3168,
  3732,
  686,
  4492,
  2583,
  2727,
  2537,
  4794],
 [2727, 709, 3508, 1223, 2477],
 [130, 2603, 990, 1612, 3757, 2307, 3824, 901],
 [1658,
  3824,
  878,
  1236,
  3716,
  413,
  353,
  1717,
  4204,
  2127,
  2570,
  1227,
  2079,
  847],
 [3685, 165, 3538, 1191, 250, 3078, 1113, 2895],
 [4316, 3970, 1612, 2285, 4105, 203, 2316, 1612, 3007, 847],
 [2556,
  1945,
  2614,
  1678,
  4926,
  4378,
  2957,
  2537,
  1236,
  2959,
  3627,
  3510,
  214,
  2477,
  4492,
  847],
 [4809, 2727, 417, 4899, 301, 474, 2658, 3174, 4188, 847],
 [130, 2603, 83, 4830, 2858, 4495],
 [3473, 179, 1189, 3096, 4806, 3909, 1008, 4910, 1612, 4370, 4268, 2902],
 [328, 4784, 3454, 1612, 1236, 3038],
 [4496, 3824, 1865, 3094, 1280, 4600, 1894, 4479],
 [4627, 1764, 1511, 1796, 1034, 1162, 4878, 3840, 1531],
 [4692, 1236, 299, 3397, 2252, 2061, 1865, 2061, 407, 48],
 [2275, 307, 4692, 4482, 4341, 3867, 98, 4906],
 [1612, 3969, 4246, 328, 3104, 3380, 3666, 930],
 [4830, 3809, 3195, 1612, 3481, 4341, 3426, 1291],
 [2362, 1433, 4214, 2022, 3592, 3450, 4455],
 [834, 2358, 1735, 4830, 1465, 1123, 1796, 4979, 3951, 2118, 4435],
 [847, 3304, 2658, 3174, 3531, 1850, 1216, 1385, 3694, 2741, 3037],
 [1937, 1862, 4825, 4157, 4272, 1451, 4035, 2727, 2460, 847],
 [39, 4876, 2769, 685, 156, 1080, 3393, 2229, 2925, 4347, 1612, 847],
 [4695, 4949, 1755, 1202, 1612, 3770, 2838],
 [3130, 4370, 1755, 208, 542, 208, 2772, 4268, 3601, 3521],
 [1226, 1151, 3976, 1465, 4004, 4816, 1613, 1264, 1264, 484, 1612, 2324],
 [3834, 3096, 4343, 4179, 3490, 3385, 4784, 319, 912, 1865, 3834, 900],
 [4179, 4508, 890, 219, 1058, 1339, 2460, 2855, 753, 4692, 252, 847],
 [3873, 1056, 2856, 890, 4627, 85, 4617, 3473],
 [116, 1724, 1755, 1334, 2467, 3033, 1460],
 [116, 1236, 3096, 165, 910, 251, 1539, 2088, 1747],
 [4832, 3245, 1252, 48, 4255, 1270, 2088, 3133],
 [2057, 1923, 3393, 4245, 1176, 2503, 244, 1222],
 [477, 1796, 3958, 1612, 4372, 1655, 653, 3804, 1847, 1132],
 [4845, 1239, 1191, 762, 4537, 2226, 2607, 2913, 2216, 3311, 3980],
 [118,
  240,
  847,
  4495,
  1942,
  4196,
  291,
  2590,
  4284,
  1862,
  3330,
  1692,
  4307,
  3823,
  3685,
  2727],
 [499, 4322, 4830, 2578, 3380, 2503, 3583],
 [1287, 1612, 3733, 1937, 4117, 1990],
 [2151, 2427, 2198, 1850, 4437, 2870, 3684, 3919, 4374, 1551, 2204, 1189],
 [2600, 2108, 1094, 2626, 542, 2578, 2823, 3785, 4749, 2741, 4288],
 [2727, 3759, 92, 1236, 2358, 2578, 3732, 3097, 208, 2326],
 [118, 4266, 146, 2867, 431, 1433, 3150, 1433],
 [556,
  2493,
  4885,
  417,
  2766,
  1612,
  2181,
  3757,
  4843,
  915,
  2493,
  1146,
  1653,
  847,
  3473,
  2008,
  339,
  3125],
 [328, 3104, 214, 1443, 4035, 928, 2968, 1874, 1674],
 [3033, 4665, 49, 163, 2808, 321, 1460, 1605, 960],
 [3380, 2302, 2374, 3514, 4830, 720, 2894, 4876],
 [4207, 4455, 19, 936, 365, 2321, 4784, 936, 3311],
 [116, 3131, 165, 2361, 4449, 4570, 1362],
 [1356, 4495, 1270, 2578, 2823, 166, 3248, 579, 333, 847],
 [4026, 1061, 1889, 807, 4712, 1612, 328, 3104, 2663],
 [3654, 1009, 4838, 2938, 457, 767, 1253, 4869, 3380],
 [534, 3531, 1256, 3627, 3510, 2631, 847, 2921],
 [2033, 2095, 3824, 2913, 4245, 118, 1612, 4374, 1869, 1325],
 [309,
  3216,
  1479,
  3279,
  2506,
  4809,
  1283,
  2537,
  1887,
  1857,
  4266,
  3510,
  136,
  598],
 [1189, 116, 2665, 3067, 2686, 1988, 4971, 1612, 990, 847],
 [3201, 2238, 2151, 3950, 3292, 4830, 921, 1984, 1859],
 [3668,
  499,
  1015,
  709,
  3582,
  3195,
  4843,
  417,
  2008,
  339,
  313,
  3292,
  3834,
  847],
 [1043, 990, 3555, 3564, 4816, 3462, 3972],
 [116, 3131, 1836, 2176, 1850, 328, 3104, 2809, 3130, 933],
 [847, 2287, 890, 3064],
 [3955, 3557, 4665, 3170, 508, 495, 4083, 1789, 156],
 [737, 3949, 4777, 1349, 2662, 1287, 3048, 530, 1280, 3977],
 [1189, 339, 1420, 3015, 1982, 1561, 4979, 4428, 4830, 1798],
 [737, 1612, 4290, 3824, 4482, 4437, 777, 4027, 2727],
 [541, 1218, 1280, 4627, 4692, 3611, 2358, 661],
 [1413, 1779, 2166, 2583, 4281, 2227, 116],
 [118, 1491, 539, 847, 165, 431, 4511, 3395],
 [1022, 1202, 1064, 1747, 1678, 1529, 2219, 4029, 3504, 1022, 402, 847],
 [10, 1777, 3693, 1721, 4455, 252, 2721, 2631, 847],
 [2870, 3716, 2863, 2268, 2820, 3971, 530, 1280, 4593, 1496, 515],
 [2823, 508, 2129, 813, 3555, 1481, 3884, 2839, 1365, 3488, 4484, 2537, 847],
 [4899, 2823, 1981, 1692, 1113, 762, 1612],
 [2881, 4692, 116, 4699, 3174, 1349, 3033, 1460],
 [2353, 4839, 92, 2269, 2088, 1485],
 [1202, 3207, 2601, 1612, 214, 4207, 973, 1734, 1433],
 [3239,
  3824,
  1862,
  3330,
  2570,
  1924,
  558,
  3285,
  1133,
  4605,
  506,
  1937,
  4117,
  1694,
  2578,
  2823],
 [1491, 3574, 1612, 4524, 1826, 973, 4614, 4268, 3500, 1190, 4208],
 [3521, 1905, 2652, 1414, 4029, 3130, 2772, 1197],
 [4426, 842, 2820, 4830, 4185, 1612, 4101, 2607],
 [80, 1612, 782, 1057, 1874, 3633, 2197, 1631],
 [156, 2954, 1690, 530, 1280, 4290, 1496, 1619],
 [174, 2354, 3285, 2543, 893, 4891, 4293, 1189, 3450, 3783, 3783, 413, 3781],
 [4909, 1057, 1642, 2855, 1957, 2166],
 [3751, 1208, 165, 642, 3684, 86, 4692, 3314, 1325],
 [4692, 2869, 2503, 3583, 4860, 3461, 1325],
 [116, 3221, 588, 1057, 2938, 2976, 3380],
 [3733, 1801, 1304, 4435, 2823, 4871, 4177, 1832, 1981],
 [4617, 1093, 3681, 1612, 4482, 2607, 2453, 3131, 3873],
 [4995, 165, 931, 34, 1236, 2699, 328, 3104],
 [431,
  4246,
  2650,
  3290,
  2683,
  4985,
  431,
  712,
  897,
  4784,
  1998,
  431,
  4492,
  3733,
  4584,
  661,
  1192,
  328,
  4492,
  243,
  2838],
 [2653, 1208, 1057, 3286, 1511, 4232, 3949, 3008],
 [1612, 214, 539, 137, 1198, 2531, 59, 847],
 [1531, 2437, 3388, 1123, 4814, 1814, 4268],
 [3104, 1493, 2506, 4197, 762, 3271, 1061],
 [3104, 1493, 2506, 165, 1612, 3783, 922, 2033, 137],
 [2727, 4307, 4877, 3953, 328, 3104, 934, 4149, 3859, 1190, 785, 847],
 [45, 4347, 2432, 558, 1190, 4889, 1280, 4611],
 [3187, 4344, 1967, 2995, 4399, 3876, 711, 3148, 2823],
 [3733,
  3222,
  1674,
  2531,
  4051,
  2688,
  847,
  4004,
  3150,
  890,
  4455,
  1474,
  3292,
  847],
 [1796, 4790, 1190, 3119, 3054, 3592, 48],
 [4281,
  2227,
  3037,
  949,
  3304,
  3969,
  1692,
  1189,
  339,
  148,
  2452,
  2039,
  2966,
  706],
 [1254,
  4495,
  4614,
  3330,
  2683,
  677,
  1887,
  2289,
  900,
  3657,
  4559,
  3594,
  2775,
  847],
 [2727, 2555, 4116, 4553, 1286, 947, 1649, 836, 4471, 1667, 1280, 847],
 [1283, 712, 2437, 2684, 91, 2031, 2275, 1767, 2437, 743],
 [4963, 1216, 813, 3976, 1850, 1612, 214, 4008, 1577],
 [541, 2638, 1865, 1692, 4614, 2706, 3785, 4830, 762, 3205, 928, 847],
 [1567, 225, 890, 1925, 4238, 1883, 3143, 3488, 3555, 211, 4532, 847],
 [1015, 2995, 4117, 4649, 3174, 473, 3716, 3092, 3885],
 [1612, 4337, 2229, 3931, 3393, 4671, 411, 1227, 2599],
 [642, 820, 1850, 2247, 4876, 2727, 4876, 1287, 849, 2942, 2537, 847],
 [990, 2727, 4547, 1280],
 [1612, 4830, 4101, 2607, 679, 87, 3290, 921],
 [118, 3899, 1633, 4402, 300, 541, 2638, 1865, 4102, 928],
 [2823, 2699, 2555, 4830, 3133, 499, 1977, 2633, 847],
 [2254,
  2678,
  3733,
  1871,
  1937,
  1947,
  3733,
  228,
  3773,
  574,
  1843,
  1612,
  2902,
  4605,
  3963,
  1015,
  3108],
 [4757, 2322, 1894, 1612, 490, 1451, 1385],
 [2727, 863, 2999, 1747, 1415, 1099, 2895],
 [1539,
  2794,
  3727,
  2940,
  1530,
  3583,
  1190,
  3574,
  3824,
  2913,
  614,
  1305,
  4536,
  2253,
  3204,
  1132],
 [2727,
  4830,
  2003,
  4149,
  2361,
  1539,
  4194,
  2155,
  542,
  1615,
  328,
  1491,
  431,
  3150,
  890],
 [1612, 4255, 4291, 299, 3060, 2358, 3851, 1465, 2916, 1350],
 [1018, 1641, 4029, 615, 4276, 4040, 1485, 3078, 888],
 [3656, 1531, 404, 7, 3601, 1511, 3592, 4692, 4825],
 [54, 3138, 1690, 4845, 1653, 2000, 1662, 825],
 [3104, 1678, 3150, 3104, 3125, 2993, 973, 1493, 2506, 2754, 928],
 [249, 1385, 4971, 2995, 855, 3193, 1491, 4434, 4692, 1059, 2270],
 [130, 2603, 1651, 3433, 4971, 344],
 [1304, 4979, 2275, 2886, 1099, 2260, 539, 2814, 4489, 4435, 3857, 499, 847],
 [3195, 4699, 4692, 2938, 1300, 1061, 2030, 89, 1612, 4509],
 [4435, 1057, 3374, 1612, 480, 4427, 2583, 3181, 3627, 1859],
 [499, 1449, 2727, 1414, 2095, 2095, 530, 4984, 4710, 1653, 317, 4437, 847],
 [4272, 3432, 2686, 3380, 1334, 1612, 3092, 874],
 [313, 2520, 2908, 212, 990, 1658],
 [1774, 1492, 1849, 3619, 1092, 4830, 4784],
 [2030, 1203, 1612, 1755, 3094, 1349, 2872],
 [2882, 4374, 1017, 973, 3160, 2754, 927, 1236],
 [1828, 2689, 1901, 1612, 3855, 3924],
 [3739,
  908,
  208,
  4141,
  3025,
  413,
  3615,
  1264,
  3775,
  4281,
  480,
  3363,
  1988,
  2956,
  4702],
 [2486, 2029, 88, 3393, 1288, 1611, 1612, 990, 1984, 847],
 [328, 2726, 3887, 4843, 3170, 431, 751, 847],
 [2580,
  1674,
  1948,
  2405,
  3193,
  4268,
  3554,
  4268,
  1904,
  4717,
  3960,
  3299,
  2825,
  2405,
  3193],
 [4738, 3716, 2808, 1948, 1470, 2526, 1516, 1099, 2895],
 [2872,
  190,
  3393,
  2144,
  3668,
  2855,
  3994,
  2976,
  2302,
  2374,
  594,
  1511,
  4383,
  4851],
 [1287, 1612, 3168, 1547, 4614, 164, 3974, 1724, 3473, 313, 2842],
 [1877, 4912, 2868, 1448, 4841, 2079, 116, 3221, 2749, 1543],
 [2555, 377, 3189, 3884, 650, 4830, 4492],
 [3964, 4830, 1981, 4004, 4435, 767, 3663, 3683, 1354, 2727],
 [298, 328, 3104, 1109, 4232, 2868, 3557, 4665, 2939, 4724],
 [4816, 1967, 165, 1747, 2870, 4511, 452, 3380, 2229],
 [1236, 1057, 4582, 4426, 842, 45, 265, 4435, 620],
 [3292, 1202, 3867, 4184, 591, 4175, 1624, 3025],
 [3104, 4784, 118, 1531, 915, 1460],
 [1236, 116, 3131, 1318, 1841, 3633, 4784],
 [4370, 3583, 1628, 2405, 1084, 767, 4710, 3804, 4692, 513],
 [737, 1132, 1658, 1421, 3685, 1132, 2420, 2324, 1189, 990, 1612],
 [4784, 2804, 1052, 31, 4240, 3131, 4869, 2499, 4455],
 [2137, 1352, 118, 1849, 1690, 3949, 1496, 4825],
 [3187, 4821, 4177, 3190, 4585, 2688, 634],
 [494, 1612, 214, 4876, 2917, 4210, 1546, 2293, 2400, 1456, 2921],
 [1282, 3450, 2365, 2512, 1874, 4237, 74, 3304],
 [4149, 1113, 3560, 3859, 4106, 1280],
 [1612, 165, 2503, 4144, 2992, 2503, 3461, 1325],
 [118, 1612, 4012, 2456, 1190, 2882, 4320, 4991, 3097, 2631],
 [49, 1612, 1338, 1732, 661, 2699, 4346],
 [1774, 4230, 49, 344, 4678, 2113, 3608, 2536],
 [1018, 1208, 165, 253, 661, 1747, 3096],
 [447, 3195, 2931, 1612, 1190, 2823, 642, 4499, 4943, 847],
 [1612, 2558, 1612, 3953, 328, 3104],
 [3450, 2494, 2707, 1836, 1612, 2229, 2086, 2519, 1260, 4435, 2921],
 [921, 1612, 4482, 4341, 2823, 4692, 1280],
 [881, 2420, 2727, 3909, 3786, 1408, 121, 4475, 1796, 410, 1408, 3786],
 [3733, 2830, 3237, 1563, 4323, 803, 2550, 847],
 [3611, 1612, 1057, 2452, 2362, 116, 1389, 3654, 2860, 2495],
 [3668, 1631, 1612, 1197, 30, 1197, 4869, 1612, 1189, 3218],
 [3548, 803, 4869, 1246, 279, 4395, 1836, 584, 4963, 1355, 3949],
 [4839, 1300, 936, 3583, 647, 3212],
 [4692, 4370, 1334, 2684, 4872, 123, 2995, 4292, 3583],
 [2426, 499, 4627, 1782, 836],
 [4435, 4370, 1491, 2408, 214, 4511, 431, 1355, 2263, 3374, 3855, 2671, 847],
 [2741,
  4476,
  480,
  4105,
  1796,
  1325,
  1612,
  2885,
  1612,
  4527,
  2603,
  1334,
  4377,
  1373,
  1896,
  227],
 [4201, 4031, 896, 1337, 1355],
 [116, 1197, 165, 4649, 4454, 3633, 2578, 4971, 1151],
 [118, 1338, 847, 4638, 1491, 159, 471, 3611, 4713, 4638],
 [4374, 4334, 2079, 225, 335, 2727, 1789, 2704, 2324, 2358, 225, 1022, 1320],
 [1612, 2246, 1755, 4008, 2633, 4501, 1236, 4627],
 [1612, 3311, 4692, 4252, 1057, 3592, 1985],
 [116, 3131, 767, 2976, 2622, 4306, 801, 535],
 [4877,
  1015,
  1628,

In [54]:
corpus[1]

'suspect u drone strike target milit pakistan region offici say'

In [55]:
onehot_repr[1]

[3048, 4692, 1740, 1690, 4290, 1662, 535, 1194, 1674, 165]

In [56]:
#Embedding represnation

In [57]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4784 1612  847]
 [   0    0    0 ... 1194 1674  165]
 [   0    0    0 ... 2867 1189 3922]
 ...
 [   0    0    0 ... 1190 3825 2777]
 [   0    0    0 ... 1996 1878 4598]
 [   0    0    0 ... 1622 4101 4341]]

In [58]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3048,
       4692, 1740, 1690, 4290, 1662,  535, 1194, 1674,  165], dtype=int32)

In [59]:

## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None

In [61]:
len(embedded_docs),y.shape

(44898, (44898,))

In [62]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [66]:
X_final.shape

(44898, 20)

In [67]:
y_final.shape

(44898,)

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33)

In [69]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.9057 - loss: 0.2281 - val_accuracy: 0.9308 - val_loss: 0.1757
Epoch 2/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9531 - loss: 0.1219 - val_accuracy: 0.9389 - val_loss: 0.1520
Epoch 3/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9658 - loss: 0.0905 - val_accuracy: 0.9370 - val_loss: 0.1794
Epoch 4/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9741 - loss: 0.0709 - val_accuracy: 0.9394 - val_loss: 0.1841
Epoch 5/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9800 - loss: 0.0542 - val_accuracy: 0.9377 - val_loss: 0.2040
Epoch 6/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9846 - loss: 0.0420 - val_accuracy: 0.9347 - val_loss: 0.2447
Epoch 7/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9888 - loss: 0.0308 - val_accuracy: 0.9350 - val_loss: 0.2442
Epoch 8/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9891 - loss: 0.0290 - val_accuracy: 0.9354 - val_loss: 0.3107
Epoch 9/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9922 - loss: 0.0207 - val_accuracy: 0.9297 - val_loss: 0.3933
Epoch 10/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9929 - loss: 0.0182 - val_accuracy: 0.9326 - val_loss: 0.3544

In [70]:
y_pred=model.predict(X_test)

464/464 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step

In [71]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [72]:
from sklearn.metrics import confusion_matrix

In [73]:
confusion_matrix(y_test,y_pred)

array([[6583,  544],
       [ 437, 7253]])

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.933792265640818

In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93      7127
           1       0.93      0.94      0.94      7690

    accuracy                           0.93     14817
   macro avg       0.93      0.93      0.93     14817
weighted avg       0.93      0.93      0.93     14817