<a href="https://colab.research.google.com/github/vipinkumarcp/NLP_Practice/blob/main/Wordtovec_and_bow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import pandas as pd

In [91]:
messages =  pd.read_csv('/content/SMSSpamCollection',sep='\t',names=['lablel','message'])

In [92]:
messages

     lablel                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [93]:
messages.shape

(5572, 2)

In [94]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [95]:
#data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [96]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [97]:
#stemming and stopwords
corpus = []
for i in range(0,len(messages)):
  # print(messages['message'][i])
  review = re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review = review.lower()
  review = review.split()
  # print(review)

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  # print(review)
  review = ' '.join(review)
  # print(review)
  corpus.append(review)

In [98]:
len(corpus)

5572

In [99]:
#creating the bag of the words

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(2,2))
#It creates a binary bag-of-words representation with a limited vocabulary of the most frequent 2500 terms.
X = cv.fit_transform(corpus).toarray()

In [100]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [101]:
y = pd.get_dummies(messages['lablel'])

In [102]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [103]:
y = y.iloc[:,1].values

In [104]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [105]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)
#

In [106]:
#prediction
y_pred = spam_detect_model.predict(X_test)

In [107]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9713004484304932
              precision    recall  f1-score   support

       False       0.97      1.00      0.98       955
        True       1.00      0.80      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115

In [108]:
#creating TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()
#

In [109]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [110]:
y_pred = spam_detect_model.predict(X_test)

In [111]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9847533632286996
              precision    recall  f1-score   support

       False       0.98      1.00      0.99       955
        True       1.00      0.89      0.94       160

    accuracy                           0.98      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.98      0.98      1115

In [112]:
#wordtovec

In [113]:
!pip install gensim
#gensim have pretrained and also we can train the model from the scratch

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)

In [114]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [115]:
vec_king = wv['king']

In [116]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [117]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [118]:
#stemming and stopwords
corpus = []
for i in range(0,len(messages)):
  # print(messages['message'][i])
  review = re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review = review.lower()
  review = review.split()
  # print(review)

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  # print(review)
  review = ' '.join(review)
  # print(review)
  corpus.append(review)

In [119]:
from nltk import sent_tokenize

In [120]:
from gensim.utils import simple_preprocess

In [121]:
corpus[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [122]:
nltk.download('punkt_tab')
#simple process concerst a list of document into lowercase token
words = []
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [123]:
words

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli',
  'over'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select',
  'receivea',
  'prize',
  'reward',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour'],
 ['mobil',
  'month',
  'entitl',
  'updat',
  'latest',
  'colour',
  'mobil',
  'camera',
  'free',
  'call',
  'mobil',
  'updat',
  'co',
  'free'],
 ['gonna',
  'home',
  'soon',
  'want',
  'talk',
  'stuff',
  'anymor',
  'tonight',
  'cri',
  'enough',
  'today'],
 ['six',
  'chanc',
  'win',
  'cash',
  'pound',
  'txt',
  'csh',
  'send',
  'cost',
  'day',
  'day',
  'tsandc',
  'appli',
  'repli',
  'hl',
  'info'],
 ['urgent',
  'week',
  'free',
  'membership',
  'prize',
  'jackpot',
  'txt',
  'word',
  'claim',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['search',
  'right',
  'word',
  'thank',
  'breather',
  'promis',
  'wont',
  'take',
  'help',
  'grant',
  'fulfil',
  'promis',
  'wonder',
  'bless',
  'time'],
 ['date', 'sunday'],
 ['use',
  'credit',
  'click',
  'wap',
  'link',
  'next',
  'txt',
  'messag',
  'click',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watch'],
 ['eh', 'rememb', 'spell', 'name', 'ye', 'naughti', 'make', 'wet'],
 ['fine', 'way', 'feel', 'way', 'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'nation',
  'team',
  'eg',
  'england',
  'tri',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['serious', 'spell', 'name'],
 ['go', 'tri', 'month', 'ha', 'ha', 'joke'],
 ['pay', 'first', 'lar', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'lunch',
  'go',
  'str',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'alreadi'],
 ['ffffffffff', 'alright', 'way', 'meet', 'sooner'],
 ['forc',
  'eat',
  'slice',
  'realli',
  'hungri',
  'tho',
  'suck',
  'mark',
  'get',
  'worri',
  'know',
  'sick',
  'turn',
  'pizza',
  'lol'],
 ['lol', 'alway', 'convinc'],
 ['catch',
  'bu',
  'fri',
  'egg',
  'make',
  'tea',
  'eat',
  'mom',
  'left',
  'dinner',
  'feel',
  'love'],
 ['back', 'amp', 'pack', 'car', 'let', 'know', 'room'],
 ['ahhh', 'work', 'vagu', 'rememb', 'feel', 'like', 'lol'],
 ['wait', 'still', 'clear', 'sure', 'sarcast', 'want', 'live', 'us'],
 ['yeah',
  'got',
  'apologet',
  'fallen',
  'actin',
  'like',
  'spoilt',
  'child',
  'got',
  'caught',
  'till',
  'go',
  'badli',
  'cheer'],
 ['tell', 'anyth'],
 ['fear', 'faint', 'housework', 'quick', 'cuppa'],
 ['thank',
  'subscript',
  'rington',
  'uk',
  'mobil',
  'charg',
  'month',
  'pleas',
  'confirm',
  'repli',
  'ye',
  'repli',
  'charg'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'time',
  'msg',
  'xuhui',
  'go',
  'learn',
  'nd',
  'may',
  'lesson',
  'am'],
 ['oop', 'let', 'know', 'roommat', 'done'],
 ['see', 'letter', 'car'],
 ['anyth', 'lor', 'decid'],
 ['hello',
  'saturday',
  'go',
  'text',
  'see',
  'decid',
  'anyth',
  'tomo',
  'tri',
  'invit',
  'anyth'],
 ['pl', 'go', 'ahead', 'watt', 'want', 'sure', 'great', 'weekend', 'abiola'],
 ['forget',
  'tell',
  'want',
  'need',
  'crave',
  'love',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummi'],
 ['rodger',
  'burn',
  'msg',
  'tri',
  'call',
  'repli',
  'sm',
  'free',
  'nokia',
  'mobil',
  'free',
  'camcord',
  'pleas',
  'call',
  'deliveri',
  'tomorrow'],
 ['see'],
 ['great', 'hope', 'like', 'man', 'well', 'endow', 'lt', 'gt', 'inch'],
 ['call', 'messag', 'miss', 'call'],
 ['get', 'hep', 'immunis', 'nigeria'],
 ['fair', 'enough', 'anyth', 'go'],
 ['yeah', 'hope', 'tyler', 'could', 'mayb', 'ask', 'around', 'bit'],
 ['know',
  'stubborn',
  'even',
  'want',
  'go',
  'hospit',
  'kept',
  'tell',
  'mark',
  'weak',
  'sucker',
  'hospit',
  'weak',
  'sucker'],
 ['think', 'first', 'time', 'saw', 'class'],
 ['gram',
  'usual',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'smarter',
  'though',
  'get',
  'almost',
  'whole',
  'second',
  'gram',
  'lt',
  'gt'],
 ['fyi', 'ride', 'earli', 'tomorrow', 'morn', 'crash', 'place', 'tonight'],
 ['wow',
  'never',
  'realiz',
  'embarass',
  'accomod',
  'thought',
  'like',
  'sinc',
  'best',
  'could',
  'alway',
  'seem',
  'happi',
  'cave',
  'sorri',
  'give',
  'sorri',
  'offer',
  'sorri',
  'room',
  'embarass'],
 ['sm',
  'ac',
  'sptv',
  'new',
  'jersey',
  'devil',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'incorrect',
  'end',
  'repli',
  'end',
  'sptv'],
 ['know', 'mallika', 'sherawat', 'yesterday', 'find', 'lt', 'url', 'gt'],
 ['congrat',
  'year',
  'special',
  'cinema',
  'pass',
  'call',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss'],
 ['sorri', 'call', 'later', 'meet'],
 ['tell', 'reach'],
 ['ye', 'gauti', 'sehwag', 'odi', 'seri'],
 ['gonna', 'pick', 'burger', 'way', 'home', 'even', 'move', 'pain', 'kill'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'situat', 'seeker'],
 ['part', 'check', 'iq'],
 ['sorri', 'roommat', 'took', 'forev', 'ok', 'come'],
 ['ok',
  'lar',
  'doubl',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'alreadi',
  'said',
  'wun',
  'cut',
  'short',
  'said',
  'cut',
  'look',
  'nice'],
 ['valu',
  'custom',
  'pleas',
  'advis',
  'follow',
  'recent',
  'review',
  'mob',
  'award',
  'bonu',
  'prize',
  'call'],
 ['today',
  'song',
  'dedic',
  'day',
  'song',
  'dedic',
  'send',
  'ur',
  'valuabl',
  'frnd',
  'first',
  'rpli'],
 ['urgent',
  'ur',
  'award',
  'complimentari',
  'trip',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'claim',
  'txt',
  'di',
  'morefrmmob',
  'ls',
  'aj'],
 ['hear', 'new', 'divorc', 'barbi', 'come', 'ken', 'stuff'],
 ['plane', 'give', 'month', 'end'],
 ['wah', 'lucki', 'man', 'save', 'money', 'hee'],
 ['finish', 'class'],
 ['hi', 'babe', 'im', 'home', 'wanna', 'someth', 'xx'],
 ['perform'],
 ['call'],
 ['wait', 'machan', 'call', 'free'],
 ['that', 'cool', 'gentleman', 'treat', 'digniti', 'respect'],
 ['like', 'peopl', 'much', 'shi', 'pa'],
 ['oper', 'lt', 'gt'],
 ['still', 'look', 'job', 'much', 'ta', 'earn'],
 ['sorri', 'call', 'later'],
 ['call', 'ah'],
 ['ok', 'way', 'home', 'hi', 'hi'],
 ['place', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'later', 'network', 'urgnt', 'sm'],
 ['real',
  'get',
  'yo',
  'need',
  'ticket',
  'one',
  'jacket',
  'done',
  'alreadi',
  'use',
  'multi'],
 ['ye',
  'start',
  'send',
  'request',
  'make',
  'pain',
  'came',
  'back',
  'back',
  'bed',
  'doubl',
  'coin',
  'factori',
  'gotta',
  'cash',
  'nitro'],
 ['realli', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah', 'stand', 'close', 'tho', 'catch', 'someth'],
 ['sorri',
  'pain',
  'ok',
  'meet',
  'anoth',
  'night',
  'spent',
  'late',
  'afternoon',
  'casualti',
  'mean',
  'done',
  'stuff',
  'moro',
  'includ',
  'time',
  'sheet',
  'sorri'],
 ['smile',
  'pleasur',
  'smile',
  'pain',
  'smile',
  'troubl',
  'pour',
  'like',
  'rain',
  'smile',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someon',
  'still',
  'love',
  'see',
  'smile'],
 ['pleas',
  'call',
  'custom',
  'servic',
  'repres',
  'am',
  'pm',
  'guarante',
  'cash',
  'prize'],
 ['havent',
  'plan',
  'buy',
  'later',
  'check',
  'alreadi',
  'lido',
  'got',
  'show',
  'afternoon',
  'finish',
  'work',
  'alreadi'],
 ['free',
  'rington',
  'wait',
  'collect',
  'simpli',
  'text',
  'password',
  'mix',
  'verifi',
  'get',
  'usher',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watch', 'telugu', 'movi', 'wat', 'abt'],
 ['see', 'finish', 'load', 'loan', 'pay'],
 ['hi',
  'wk',
  'ok',
  'hol',
  'ye',
  'bit',
  'run',
  'forgot',
  'hairdress',
  'appoint',
  'four',
  'need',
  'get',
  'home',
  'shower',
  'beforehand',
  'caus',
  'prob'],
 ['see', 'cup', 'coffe', 'anim'],
 ['pleas', 'text', 'anymor', 'noth', 'els', 'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'legal',
  'wen',
  'pick',
  'ave',
  'am',
  'xx'],
 ['still', 'look', 'car', 'buy', 'gone', 'the', 'drive', 'test', 'yet'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['wow',
  'right',
  'mean',
  'guess',
  'gave',
  'boston',
  'men',
  'chang',
  'search',
  'locat',
  'nyc',
  'someth',
  'chang',
  'cuz',
  'signin',
  'page',
  'still',
  'say',
  'boston'],
 ['umma', 'life', 'vava', 'umma', 'love', 'lot', 'dear'],
 ['thank',
  'lot',
  'wish',
  'birthday',
  'thank',
  'make',
  'birthday',
  'truli',
  'memor'],
 ['aight', 'hit', 'get', 'cash'],
 ['would', 'ip', 'address', 'test', 'consid', 'comput', 'minecraft', 'server'],
 ['know',
  'grumpi',
  'old',
  'peopl',
  'mom',
  'like',
  'better',
  'lie',
  'alway',
  'one',
  'play',
  'joke'],
 ['dont', 'worri', 'guess', 'busi'],
 ['plural', 'noun', 'research'],
 ['go', 'dinner', 'msg'],
 ['ok',
  'wif',
  'co',
  'like',
  'tri',
  'new',
  'thing',
  'scare',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'loud'],
 ['gent',
  'tri',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guarante',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentenc',
  'formal',
  'anyway',
  'fine',
  'juz',
  'tt',
  'eatin',
  'much',
  'puttin',
  'weight',
  'haha',
  'anythin',
  'special',
  'happen'],
 ['enter',
  'cabin',
  'pa',
  'said',
  'happi',
  'day',
  'boss',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invit',
  'apart',
  'went'],
 ['winner',
  'special',
  'select',
  'receiv',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'oper',
  'claim',
  'min'],
 ['goodo',
  'ye',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'tortilla',
  'need'],
 ['hmm', 'uncl', 'inform', 'pay', 'school', 'directli', 'pl', 'buy', 'food'],
 ['privat',
  'account',
  'statement',
  'show',
  'unredeem',
  'bonu',
  'point',
  'claim',
  'call',
  'identifi',
  'code',
  'expir'],
 ['urgent',
  'mobil',
  'award',
  'bonu',
  'caller',
  'prize',
  'final',
  'tri',
  'contact',
  'call',
  'landlin',
  'box',
  'wr',
  'ppm'],
 ['new', 'address', 'appl', 'pair', 'malarki'],
 ['today',
  'voda',
  'number',
  'end',
  'select',
  'receiv',
  'award',
  'match',
  'pleas',
  'call',
  'quot',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['go', 'sao', 'mu', 'today', 'done'],
 ['predict', 'wat', 'time', 'finish', 'buy'],
 ['good', 'stuff'],
 ['know',
  'yetund',
  'sent',
  'money',
  'yet',
  'sent',
  'text',
  'bother',
  'send',
  'dont',
  'involv',
  'anyth',
  'impos',
  'anyth',
  'first',
  'place',
  'apologis'],
 ['room'],
 ['hey',
  'girl',
  'hope',
  'well',
  'del',
  'bak',
  'long',
  'time',
  'give',
  'call',
  'sum',
  'time',
  'lucyxx'],
 ['much', 'cost'],
 ['home'],
 ['dear', 'call', 'tmorrow', 'pl', 'accomod'],
 ['first', 'answer', 'question'],
 ['sunshin',
  'quiz',
  'wkli',
  'win',
  'top',
  'soni',
  'dvd',
  'player',
  'know',
  'countri',
  'algarv',
  'txt',
  'ansr',
  'sp',
  'tyron'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dog',
  'locat',
  'sent',
  'direct',
  'ur',
  'mob',
  'join',
  'uk',
  'largest',
  'dog',
  'network',
  'bt',
  'txting',
  'gravel',
  'nt',
  'ec',
  'msg'],
 ['haf', 'msn', 'yiju', 'hotmail', 'com'],
 ['call', 'meet'],
 ['check', 'room', 'befor', 'activ'],
 ['rcv',
  'msg',
  'chat',
  'svc',
  'free',
  'hardcor',
  'servic',
  'text',
  'go',
  'get',
  'noth',
  'must',
  'age',
  'verifi',
  'yr',
  'network',
  'tri'],
 ['got', 'lazi', 'type', 'forgot', 'lect', 'saw', 'pouch', 'like', 'nice'],
 ['text', 'way'],
 ['sir', 'wait', 'mail'],
 ['swt',
  'thought',
  'nver',
  'get',
  'tire',
  'littl',
  'thing',
  'lovabl',
  'person',
  'coz',
  'somtim',
  'littl',
  'thing',
  'occupi',
  'biggest',
  'part',
  'heart',
  'gud',
  'ni'],
 ['know', 'pl', 'open', 'back'],
 ['ye', 'see', 'ya', 'dot'],
 ['what', 'staff', 'name', 'take', 'class', 'us'],
 ['freemsg',
  'repli',
  'text',
  'randi',
  'sexi',
  'femal',
  'live',
  'local',
  'luv',
  'hear',
  'netcollex',
  'ltd',
  'per',
  'msg',
  'repli',
  'stop',
  'end'],
 ['ummma', 'call', 'check', 'life', 'begin', 'qatar', 'pl', 'pray', 'hard'],
 ['delet', 'contact'],
 ['sindu', 'got', 'job', 'birla', 'soft'],
 ['wine', 'flow', 'never'],
 ['yup', 'thk', 'cine', 'better', 'co', 'need', 'go', 'plaza', 'mah'],
 ['ok', 'ur', 'typic', 'repli'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['everywher',
  'dirt',
  'floor',
  'window',
  'even',
  'shirt',
  'sometim',
  'open',
  'mouth',
  'come',
  'flow',
  'dream',
  'world',
  'without',
  'half',
  'chore',
  'time',
  'joy',
  'lot',
  'tv',
  'show',
  'see',
  'guess',
  'like',
  'thing',
  'must',
  'exist',
  'like',
  'rain',
  'hail',
  'mist',
  'time',
  'done',
  'becom',
  'one'],
 ['aaooooright', 'work'],
 ['leav', 'hous'],
 ['hello',
  'love',
  'get',
  'interview',
  'today',
  'happi',
  'good',
  'boy',
  'think',
  'miss'],
 ['custom',
  'servic',
  'annonc',
  'new',
  'year',
  'deliveri',
  'wait',
  'pleas',
  'call',
  'arrang',
  'deliveri'],
 ['winner',
  'special',
  'select',
  'receiv',
  'cash',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'oper',
  'claim'],
 ['keep',
  'safe',
  'need',
  'miss',
  'alreadi',
  'envi',
  'everyon',
  'see',
  'real',
  'life'],
 ['new', 'car', 'hous', 'parent', 'new', 'job', 'hand'],
 ['love', 'excit', 'day', 'spend', 'make', 'happi'],
 ['pl',
  'stop',
  'bootydeli',
  'invit',
  'friend',
  'repli',
  'ye',
  'see',
  'www',
  'sm',
  'ac',
  'bootydeli',
  'stop',
  'send',
  'stop',
  'frnd'],
 ['bangbab',
  'ur',
  'order',
  'way',
  'receiv',
  'servic',
  'msg',
  'download',
  'ur',
  'content',
  'goto',
  'wap',
  'bangb',
  'tv',
  'ur',
  'mobil',
  'internet',
  'servic',
  'menu'],
 ['place', 'ur', 'point', 'cultur', 'modul', 'alreadi'],
 ['urgent',
  'tri',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guarante',
  'call',
  'claim',
  'code',
  'valid',
  'hr'],
 ['hi', 'frnd', 'best', 'way', 'avoid', 'missunderstd', 'wit', 'belov', 'one'],
 ['great', 'escap', 'fanci', 'bridg', 'need', 'lager', 'see', 'tomo'],
 ['ye', 'complet', 'form', 'clark', 'also', 'utter', 'wast'],
 ['sir', 'need', 'axi', 'bank', 'account', 'bank', 'address'],
 ['hmmm',
  'thk',
  'sure',
  'got',
  'time',
  'hop',
  'ard',
  'ya',
  'go',
  'free',
  'abt',
  'muz',
  'call',
  'discuss',
  'liao'],
 ['time', 'come', 'later'],
 ['bloodi',
  'hell',
  'cant',
  'believ',
  'forgot',
  'surnam',
  'mr',
  'ill',
  'give',
  'clue',
  'spanish',
  'begin'],
 ['well', 'gonna', 'finish', 'bath', 'good', 'fine', 'night'],
 ['let', 'know', 'got', 'money', 'carlo', 'make', 'call'],
 ['still', 'go', 'mall'],
 ['turn',
  'friend',
  'stay',
  'whole',
  'show',
  'back',
  'til',
  'lt',
  'gt',
  'feel',
  'free',
  'go',
  'ahead',
  'smoke',
  'lt',
  'gt',
  'worth'],
 ['text', 'doesnt', 'repli', 'let', 'know', 'log'],
 ['hi',
  'spoke',
  'maneesha',
  'like',
  'know',
  'satisfi',
  'experi',
  'repli',
  'toll',
  'free',
  'ye'],
 ['lift',
  'hope',
  'offer',
  'money',
  'need',
  'especi',
  'end',
  'month',
  'approach',
  'hurt',
  'studi',
  'anyway',
  'gr',
  'weekend'],
 ['lol', 'trust'],
 ['ok', 'gentleman', 'treat', 'digniti', 'respect'],
 ['guy', 'close'],
 ['go', 'noth', 'great', 'bye'],
 ['hello',
  'handsom',
  'find',
  'job',
  'lazi',
  'work',
  'toward',
  'get',
  'back',
  'net',
  'mummi',
  'boytoy',
  'miss'],
 ['haha', 'awesom', 'minut'],
 ['pleas',
  'call',
  'custom',
  'servic',
  'repres',
  'freephon',
  'am',
  'pm',
  'guarante',
  'cash',
  'prize'],
 ['got', 'xma', 'radio', 'time', 'get'],
 ['ju',
  'reach',
  'home',
  'go',
  'bath',
  'first',
  'si',
  'use',
  'net',
  'tell',
  'finish'],
 ['uniqu', 'enough', 'find', 'th', 'august', 'www', 'areyouuniqu', 'co', 'uk'],
 ['sorri',
  'join',
  'leagu',
  'peopl',
  'dont',
  'keep',
  'touch',
  'mean',
  'great',
  'deal',
  'friend',
  'time',
  'even',
  'great',
  'person',
  'cost',
  'great',
  'week'],
 ['hi', 'final', 'complet', 'cours'],
 ['stop',
  'howev',
  'suggest',
  'stay',
  'someon',
  'abl',
  'give',
  'or',
  'everi',
  'stool'],
 ['hope', 'settl', 'new', 'school', 'year', 'wishin', 'gr', 'day'],
 ['gud', 'mrng', 'dear', 'hav', 'nice', 'day'],
 ['got', 'person', 'stori'],
 ['hamster', 'dead', 'hey', 'tmr', 'meet', 'pm', 'orchard', 'mrt'],
 ['hi',
  'kate',
  'even',
  'hope',
  'see',
  'tomorrow',
  'bit',
  'bloodi',
  'babyjontet',
  'txt',
  'back',
  'xxx'],
 ['found', 'enc', 'lt', 'gt'],
 ['sent', 'lt', 'gt', 'buck'],
 ['hello',
  'darlin',
  'ive',
  'finish',
  'colleg',
  'txt',
  'finish',
  'love',
  'kate',
  'xxx'],
 ['account',
  'refil',
  'success',
  'inr',
  'lt',
  'decim',
  'gt',
  'keralacircl',
  'prepaid',
  'account',
  'balanc',
  'rs',
  'lt',
  'decim',
  'gt',
  'transact',
  'id',
  'kr',
  'lt',
  'gt'],
 ['goodmorn', 'sleep', 'ga'],
 ['call', 'alter', 'ok'],
 ['say',
  'like',
  'dat',
  'dun',
  'buy',
  'ericsson',
  'oso',
  'cannot',
  'oredi',
  'lar'],
 ['enter',
  'cabin',
  'pa',
  'said',
  'happi',
  'day',
  'boss',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invit',
  'apart',
  'went'],
 ['aight', 'yo', 'dat', 'straight', 'dogg'],
 ['pleas',
  'give',
  'us',
  'connect',
  'today',
  'lt',
  'decim',
  'gt',
  'refund',
  'bill'],
 ['shoot', 'big', 'load', 'get', 'readi'],
 ['bruv', 'hope', 'great', 'break', 'reward', 'semest'],
 ['home', 'alway', 'chat'],
 ['good', 'studi', 'well'],
 ['yup', 'noe', 'leh'],
 ['sound', 'great', 'home'],
 ['final', 'match', 'head', 'toward', 'draw', 'predict'],
 ['tire', 'slept', 'well', 'past', 'night'],
 ['easi', 'ah', 'sen', 'got', 'select', 'mean', 'good'],
 ['take', 'exam', 'march'],
 ['yeah',
  'think',
  'use',
  'gt',
  'atm',
  'regist',
  'sure',
  'anyway',
  'help',
  'let',
  'know',
  'sure',
  'readi'],
 ['ok', 'prob', 'take', 'ur', 'time'],
 ['os',
  'call',
  'ubandu',
  'run',
  'without',
  'instal',
  'hard',
  'disk',
  'use',
  'os',
  'copi',
  'import',
  'file',
  'system',
  'give',
  'repair',
  'shop'],
 ['sorri', 'call', 'later'],
 ['say',
  'leh',
  'cours',
  'noth',
  'happen',
  'lar',
  'say',
  'romant',
  'ju',
  'bit',
  'lor',
  'thk',
  'nite',
  'sceneri',
  'nice',
  'leh'],
 ['new',
  'mobil',
  'must',
  'go',
  'txt',
  'nokia',
  'collect',
  'today',
  'www',
  'tc',
  'biz',
  'optout',
  'gbp',
  'mtmsg'],
 ['would', 'realli', 'appreci', 'call', 'need', 'someon', 'talk'],
 ['meet',
  'ur',
  'dream',
  'partner',
  'soon',
  'ur',
  'career',
  'flyng',
  'start',
  'find',
  'free',
  'txt',
  'horo',
  'follow',
  'ur',
  'star',
  'sign',
  'horo',
  'ari'],
 ['hey', 'compani', 'elama', 'po', 'mudyadhu'],
 ['life',
  'strict',
  'teacher',
  'bcoz',

In [124]:
import gensim

In [125]:
#This trains a Word2Vec model that learns word meanings using a context window of 5 and ignores rare words appearing less than twice.
model = gensim.models.Word2Vec(words,min_count=2,window=5)

In [126]:
#It returns the vocabulary (list of learned words) from the Word2Vec model, ordered by frequency.
model.wv.index_to_key

['call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'day',
 'ok',
 'free',
 'know',
 'love',
 'like',
 'time',
 'good',
 'want',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'take',
 'stop',
 'see',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'still',
 'tell',
 'mobil',
 'back',
 'da',
 'dont',
 'make',
 'phone',
 'pleas',
 'week',
 'hi',
 'say',
 'new',
 'work',
 'later',
 'pl',
 'hope',
 'miss',
 'ask',
 'co',
 'msg',
 'min',
 'meet',
 'dear',
 'night',
 'messag',
 'happi',
 'wait',
 'well',
 'give',
 'thing',
 'tri',
 'much',
 'great',
 'oh',
 'claim',
 'wat',
 'hey',
 'number',
 'friend',
 'thank',
 'way',
 'ye',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'even',
 'tomorrow',
 'win',
 'pick',
 'alreadi',
 'care',
 'said',
 'cash',
 'im',
 'amp',
 'leav',
 'yeah',
 'tone',
 'realli',
 'babe',
 'find',
 'life',
 'morn',
 'sleep',
 'last',
 'keep',
 'servic',
 'year',
 'uk',
 'nokia',
 'sure',
 'com',
 'would',
 'buy',
 'anyth',
 'use',
 'contact',
 'start',
 'also',
 'lol',
 'wish',
 'urgent',
 'everi',
 'look',
 'smile',
 'sent',
 'end',
 'show',
 'someth',
 'watch',
 'award',
 'gud',
 'us',
 'finish',
 'cant',
 'place',
 'box',
 'first',
 'help',
 'person',
 'guy',
 'someon',
 'special',
 'chat',
 'went',
 'nice',
 'next',
 'tonight',
 'custom',
 'late',
 'talk',
 'soon',
 'word',
 'around',
 'collect',
 'money',
 'could',
 'mani',
 'name',
 'per',
 'ya',
 'plan',
 'sm',
 'alway',
 'gonna',
 'wan',
 'live',
 'minut',
 'lot',
 'check',
 'shop',
 'pm',
 'dun',
 'st',
 'told',
 'mean',
 'hello',
 'th',
 'heart',
 'girl',
 'fine',
 'month',
 'hour',
 'may',
 'haha',
 'guarante',
 'peopl',
 'reach',
 'best',
 'thk',
 'happen',
 'yet',
 'offer',
 'done',
 'god',
 'ppm',
 'thought',
 'play',
 'cost',
 'fuck',
 'line',
 'holiday',
 'class',
 'stuff',
 'bit',
 'man',
 'car',
 'lunch',
 'receiv',
 'enjoy',
 'ill',
 'hous',
 'draw',
 'wk',
 'job',
 'never',
 'mayb',
 'eat',
 'problem',
 'cs',
 'that',
 'worri',
 'mind',
 'readi',
 'account',
 'hr',
 'better',
 'cool',
 'yup',
 'dat',
 'guess',
 'drive',
 'long',
 'rington',
 'date',
 'pobox',
 'rate',
 'quit',
 'game',
 'boy',
 'weekend',
 'pay',
 'chanc',
 'luv',
 'real',
 'half',
 'wonder',
 'latest',
 'world',
 'bring',
 'book',
 'sir',
 'bt',
 'po',
 'yo',
 'room',
 'pic',
 'voucher',
 'noth',
 'wanna',
 'sweet',
 'camera',
 'lar',
 'shit',
 'big',
 'liao',
 'join',
 'anoth',
 'charg',
 'question',
 'put',
 'kiss',
 'stay',
 'age',
 'landlin',
 'birthday',
 'ah',
 'dinner',
 'select',
 'xxx',
 'land',
 'ever',
 'might',
 'video',
 'ju',
 'rememb',
 'network',
 'speak',
 'actual',
 'anyway',
 'hear',
 'di',
 'wont',
 'appli',
 'probabl',
 'orang',
 'two',
 'babi',
 'thanx',
 'tv',
 'dream',
 'aight',
 'chang',
 'hurt',
 'pa',
 'run',
 'nd',
 'fun',
 'earli',
 'final',
 'point',
 'princess',
 'bad',
 'den',
 'offic',
 'sat',
 'shall',
 'nite',
 'answer',
 'forgot',
 'bed',
 'part',
 'left',
 'dunno',
 'made',
 'gift',
 'wake',
 'walk',
 'easi',
 'pain',
 'code',
 'dad',
 'wife',
 'true',
 'didnt',
 'everyth',
 'face',
 'sound',
 'leh',
 'littl',
 'mail',
 'xx',
 'frnd',
 'mate',
 'town',
 'bore',
 'detail',
 'yr',
 'school',
 'movi',
 'afternoon',
 'bu',
 'pound',
 'enough',
 'await',
 'post',
 'read',
 'lose',
 'tmr',
 'without',
 'poli',
 'import',
 'hav',
 'xma',
 'sexi',
 'must',
 'test',
 'price',
 'okay',
 'came',
 'sinc',
 'decid',
 'credit',
 'updat',
 'valid',
 'though',
 'wif',
 'drink',
 'wot',
 'abl',
 'smoke',
 'til',
 'abt',
 'close',
 'mob',
 'lesson',
 'colour',
 'set',
 'goe',
 'entri',
 'plu',
 'away',
 'de',
 'plz',
 'music',
 'decim',
 'bath',
 'order',
 'enter',
 'juz',
 'wen',
 'drop',
 'attempt',
 'beauti',
 'dude',
 'weekli',
 'hand',
 'top',
 'busi',
 'els',
 'havent',
 'hair',
 'doubl',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'onlin',
 'friendship',
 'optout',
 'head',
 'oso',
 'id',
 'coz',
 'haf',
 'food',
 'trip',
 'invit',
 'net',
 'famili',
 'sch',
 'either',
 'club',
 'hot',
 'ring',
 'hold',
 'gr',
 'open',
 'player',
 'inform',
 'address',
 'deliveri',
 'ard',
 'nation',
 'search',
 'sad',
 'togeth',
 'sae',
 'tot',
 'mth',
 'full',
 'wid',
 'stori',
 'touch',
 'si',
 'believ',
 'complet',
 'nt',
 'caus',
 'bonu',
 'second',
 'mom',
 'http',
 'brother',
 'murder',
 'email',
 'train',
 'mum',
 'listen',
 'eve',
 'huh',
 'reason',
 'chikku',
 'row',
 'oki',
 'noe',
 'studi',
 'content',
 'match',
 'old',
 'forget',
 'info',
 'anyon',
 'rite',
 'pub',
 'simpl',
 'unsubscrib',
 'park',
 'wil',
 'die',
 'break',
 'awesom',
 'parent',
 'everyon',
 'dog',
 'expir',
 'privat',
 'took',
 'congrat',
 'tomo',
 'fri',
 'aft',
 'news',
 'hl',
 'treat',
 'auction',
 'sell',
 'laugh',
 'neva',
 'mine',
 'opt',
 'gd',
 'current',
 'valentin',
 'sister',
 'card',
 'sort',
 'choos',
 'angri',
 'reveal',
 'compani',
 'tc',
 'fanci',
 'statement',
 'prob',
 'download',
 'move',
 'am',
 'tho',
 'valu',
 'caller',
 'avail',
 'alon',
 'understand',
 'gal',
 'knw',
 'sun',
 'whatev',
 'visit',
 'forward',
 'colleg',
 'found',
 'worth',
 'carlo',
 'bank',
 'what',
 'type',
 'ticket',
 'lucki',
 'pass',
 'seem',
 'joke',
 'how',
 'surpris',
 'parti',
 'sit',
 'fast',
 'outsid',
 'nyt',
 'kind',
 'welcom',
 'bout',
 'mobileupd',
 'return',
 'fone',
 'far',
 'anytim',
 'congratul',
 'tel',
 'secret',
 'gbp',
 'exam',
 'bill',
 'ga',
 'boytoy',
 'log',
 'hard',
 'ltd',
 'ni',
 'identifi',
 'uncl',
 'friday',
 'hit',
 'gone',
 'oper',
 'save',
 'song',
 'usual',
 'saturday',
 'smth',
 'ha',
 'winner',
 'tht',
 'chennai',
 'least',
 'wrong',
 'drug',
 'clean',
 'sea',
 'pretti',
 'nope',
 'term',
 'cum',
 'remov',
 'differ',
 'ad',
 'project',
 'suite',
 'interest',
 'light',
 'case',
 'oredi',
 'goodmorn',
 'rs',
 'darlin',
 'mrng',
 'wit',
 'quiz',
 'mu',
 'rain',
 'follow',
 'cut',
 'camcord',
 'confirm',
 'crazi',
 'support',
 'earlier',
 'snow',
 'kid',
 'sub',
 'savamob',
 'frm',
 'scream',
 'suppos',
 'ten',
 'rock',
 'jay',
 'blue',
 'unlimit',
 'cd',
 'fix',
 'fr',
 'meant',
 'cours',
 'spend',
 'tire',
 'hmm',
 'comput',
 'correct',
 'whole',
 'hungri',
 'wq',
 'sunday',
 'freemsg',
 'wkli',
 'father',
 'fren',
 'john',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'store',
 'eye',
 'an',
 'sex',
 'paper',
 'area',
 'yar',
 'marri',
 'redeem',
 'un',
 'within',
 'fight',
 'sk',
 'india',
 'ass',
 'coupl',
 'motorola',
 'moment',
 'ago',
 'figur',
 'christma',
 'lost',
 'normal',
 'bslvyl',
 'stupid',
 'singl',
 'dnt',
 'side',
 'march',
 'balanc',
 'mr',
 'hmmm',
 'joy',
 'wine',
 'pray',
 'activ',
 'felt',
 'mah',
 'shower',
 'load',
 'hee',
 'etc',
 'almost',
 'catch',
 'turn',
 'eh',
 'promis',
 'reward',
 'press',
 'difficult',
 'grin',
 'fill',
 'heard',
 'photo',
 'extra',
 'ugh',
 'darren',
 'gym',
 'remind',
 'max',
 'ladi',
 'ipod',
 'rent',
 'doin',
 'rental',
 'slow',
 'seen',
 'met',
 'ish',
 'via',
 'ge',
 'swing',
 'disturb',
 'laptop',
 'teach',
 'bcoz',
 'semest',
 'connect',
 'deal',
 'safe',
 'sometim',
 'direct',
 'askd',
 'stand',
 'gotta',
 'complimentari',
 'red',
 'ac',
 'wow',
 'hospit',
 'crave',
 'cheer',
 'comp',
 'polic',
 'slowli',
 'fact',
 'fantasi',
 'nobodi',
 'cancel',
 'convey',
 'truth',
 'asap',
 'whenev',
 'fall',
 'possibl',
 'idea',
 'noon',
 'door',
 'warm',
 'blood',
 'member',
 'silent',
 'monday',
 'yep',
 'share',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebodi',
 'hmv',
 'wana',
 'lover',
 'expect',
 'road',
 'regist',
 'kate',
 'orchard',
 'muz',
 'lovabl',
 'txting',
 'page',
 'loan',
 'includ',
 'rpli',
 'abiola',
 'comin',
 'eg',
 'link',
 'wap',
 'copi',
 'request',
 'usf',
 'std',
 'empti',
 'med',
 'cook',
 'excus',
 'hw',
 'cover',
 'write',
 'bb',
 'energi',
 'doctor',
 'digit',
 'regard',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwis',
 'poor',
 'wed',
 'gettin',
 'bag',
 'getz',
 'summer',
 'glad',
 'fantast',
 'gap',
 'king',
 'ho',
 'ts',
 'indian',
 'em',
 'cheap',
 'across',
 'children',
 'no',
 'less',
 'opinion',
 'near',
 'water',
 'style',
 'wc',
 'ldn',
 'voic',
 'mm',
 'mistak',
 'woke',
 'rakhesh',
 'custcar',
 'access',
 'immedi',
 'record',
 'merri',
 'somewher',
 'tonit',
 'deep',
 'admir',
 'kick',
 'street',
 'sign',
 'trust',
 'wast',
 'soni',
 'del',
 'quot',
 'apart',
 'men',
 'gave',
 'repres',
 'il',
 'recent',
 'short',
 'forev',
 'situat',
 'oop',
 'sick',
 'england',
 'bless',
 'callertun',
 'nah',
 'cup',
 'la',
 'tear',
 'sofa',
 'colleagu',
 'flag',
 'thinkin',
 'list',
 'excel',
 'arriv',
 'natur',
 'total',
 'moral',
 'other',
 'mode',
 'mon',
 'deliv',
 'hiya',
 'wear',
 'mo',
 'iam',
 'gay',
 'greet',
 'mid',
 'user',
 'tampa',
 'chariti',
 'comuk',
 'bid',
 'norm',
 'subscrib',
 'add',
 'bold',
 'xy',
 'pc',
 'hurri',
 'hotel',
 'self',
 'meh',
 'depend',
 'result',
 'kinda',
 'logo',
 'none',
 'al',
 'refer',
 'bluetooth',
 'basic',
 'urself',
 'round',
 'rcvd',
 'cake',
 'power',
 'accept',
 'sport',
 'rose',
 'teas',
 'unless',
 'definit',
 'ldew',
 'goodnight',
 'flirt',
 'appreci',
 'ive',
 'mrt',
 'dead',
 'especi',
 'lift',
 'doesnt',
 'becom',
 'lect',
 'lazi',
 'sunshin',
 'app',
 'flight',
 'boss',
 'coffe',
 'password',
 'ip',
 'bx',
 'ice',
 'mark',
 'serious',
 'issu',
 'mood',
 'pix',
 'manag',
 'er',
 'wednesday',
 'insid',
 'respons',
 'south',
 'vl',
 'honey',
 'cute',
 'black',
 'process',
 'miracl',
 'medic',
 'travel',
 'moon',
 'omg',
 'slave',
 'space',
 'librari',
 'student',
 'bedroom',
 'tuesday',
 'longer',
 'offici',
 'alex',
 'futur',
 'euro',
 'ar',
 'present',
 ...]

In [127]:
model.corpus_count

5565

In [128]:
model.wv.similar_by_word('claim')

[('award', 0.9994741678237915),
 ('call', 0.9994145035743713),
 ('cash', 0.9993594288825989),
 ('prize', 0.9993182420730591),
 ('mobil', 0.9992076754570007),
 ('line', 0.999197781085968),
 ('number', 0.9991769790649414),
 ('free', 0.9991141557693481),
 ('land', 0.9991036653518677),
 ('pleas', 0.9990922212600708)]

In [129]:
model.wv['kid'].shape

(100,)

In [139]:
import numpy as np
#This function converts a document into a single vector by averaging the Word2Vec embeddings of its words.

def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.key_to_index]

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [131]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

In [140]:
from tqdm import tqdm

In [141]:
words[70]

['wah', 'lucki', 'man', 'save', 'money', 'hee']

In [134]:
type(model.wv.index_to_key)

list

In [142]:
X = []
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

100%|██████████| 5565/5565 [00:00<00:00, 5750.74it/s]

In [136]:
type(X)

list

In [143]:
X_new = np.array(X)

In [144]:
X_new

array([[-0.16478182,  0.19227453,  0.04753439, ..., -0.17472167,
         0.07086299,  0.01620953],
       [-0.12831983,  0.1425377 ,  0.03277833, ..., -0.12280244,
         0.05431309,  0.01284618],
       [-0.15562078,  0.18469958,  0.04447957, ..., -0.1677243 ,
         0.0734539 ,  0.01846037],
       ...,
       [-0.03758832,  0.03881387,  0.00888993, ..., -0.03848367,
         0.02248196,  0.0078107 ],
       [-0.19111969,  0.21792173,  0.05552272, ..., -0.19794343,
         0.08566872,  0.02132079],
       [-0.12948669,  0.1438521 ,  0.03472173, ..., -0.13511048,
         0.05727084,  0.01567315]])

In [145]:
X_new[0].shape

(100,)

In [146]:
words[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [147]:
X_new[0]

array([-0.16478182,  0.19227453,  0.04753439, -0.03156028,  0.07126959,
       -0.41231927,  0.13785858,  0.5454945 , -0.08451745, -0.14228249,
       -0.18532932, -0.33846292, -0.06100662,  0.04747202,  0.05629427,
       -0.20891541,  0.03371902, -0.34054103, -0.00474502, -0.47928366,
        0.09643838,  0.18166173,  0.10673239, -0.16113403, -0.07666782,
       -0.00066607, -0.23307256, -0.24428891, -0.21410698,  0.12151417,
        0.22069953,  0.04966409,  0.04876265, -0.19318028, -0.12865464,
        0.35319683, -0.04499839, -0.19988036, -0.1716461 , -0.44470087,
        0.02551602, -0.18412012, -0.05283576,  0.0328652 ,  0.24954289,
       -0.10985485, -0.18875712, -0.16236898,  0.17694847,  0.23839219,
        0.12070217, -0.28518978, -0.09518144,  0.00951265, -0.20965463,
        0.19346863,  0.12043247,  0.02231775, -0.24054246,  0.05722311,
        0.10254013,  0.10712395, -0.06918103, -0.07158563, -0.36183164,
        0.13902079,  0.08653989,  0.18911368, -0.2139854 ,  0.23576295,
       -0.18453495,  0.1257755 ,  0.22939724, -0.07784656,  0.32656485,
        0.17582209,  0.02078252, -0.08413997, -0.25310287,  0.11596731,
       -0.07594389,  0.04157462, -0.23767118,  0.40832898, -0.01530306,
        0.050299  , -0.00665762,  0.36121938,  0.30321091,  0.01378918,
        0.35164198,  0.07402911, -0.00606826,  0.09497098,  0.52083749,
        0.25025648,  0.21108274, -0.17472167,  0.07086299,  0.01620953])

In [148]:
#Text → Tokenized words → Word2Vec → Average → X_new